### ISSUE TITLE
Compilation Error HighlyConfigurableWheelv1.33.scad

### ISSUE THREAD

**Issue by Karijn** [alexfranke/Highly-Configurable-Wheel#2]
Hi,
# I got the following error with v 1.33

Loaded design 'C:/Users/karijn/Documents/Things/Wheels/Highly-Configurable-Wheel-master/source/HighlyConfigurableWheelv1.33.scad'.
Parser error in line 1125: syntax error
# ERROR: Compilation failed!

It turns out that there is one 'bracket '} missing.
When I add one on line 1039 the script compiles OK.

Greetings,

Karijn Wessing
k.wessing@in2tech.nl

**Comment by intensite** [comment]
Just downloaded today 2020-03-07 and the bug is still there :-(

**Comment by Karijn** [comment]
one more
for dropdown lists in the customizer, place the options between square brackets

x = "cat" ; // [cat, dog, mouse ]

**Comment by Karijn** [comment]
no, i got this library on github
