### ISSUE TITLE
DEPRECATED: The assign() module will be removed in future releases. Use a regular assignment instead. 

### ISSUE THREAD

**Issue by CBDesignS** [alexfranke/Highly-Configurable-Wheel#3]
It looks as if there have been a few changes over the passing years. I have just used your scad to generate a wheel for a project to see if the design will work before I shell out for a set of factory made rims. When I opened the file and started to tweak the settings I noticed that open scad gave the following warning in the compiler window. 

DEPRECATED: The assign() module will be removed in future releases. Use a regular assignment instead. 

I have no idea if it may be a hard to fix problem but as it stands it is only a warning and it does compile and produce a working stl file.

this is just a heads up to possible failures in the future.
Sirhc

**Comment by robertmartin** [comment]
I hope this get's fixed as I would like to keep using this in the future.

**Comment by alexfranke** [comment]
@robertmartin  thanks for the nudge. Can you try the current version here in github and lmk if it works out okay for you?

**Comment by alexfranke** [comment]
@CBDesignS Thanks for the initial report!
